---
- name: Alias kubectl
  shell: snap alias microk8s.kubectl kubectl
  args:
    executable: /bin/bash

- name: check zsh is present
  shell: which zsh
  register: result
  ignore_errors: True

- name: Debug 
  debug:
    msg: "{{ result }}"

- name: Alias docker
  shell: snap alias microk8s.kubectl kubectl
  args:
    executable: /bin/zsh
  when: result.rc == 0